### ISSUE TITLE
Bert with huggingface

### ISSUE THREAD

**Issue by nadia-felix** [neuralmind-ai/portuguese-bert#11]
We have had this error when i try to use the portuguese neuralmind:

ValueError: Unrecognized model in neuralmind_model_tensor/.

I am running this:
python examples/run_glue.py --model_type bert --model_name_or_path neuralmind_model_tensor/ --task_name tweetsent --do_train --do_eval --do_lower_case --data_dir $SENT_DIR/ --max_seq_length 128 --per_gpu_train_batch_size 32 --learning_rate 2e-5 --num_train_epochs 1.0  --output_dir /tmp/output/

What can be this?

**Comment by pvcastro** [comment]
Hi @nadia-felix , the actual model_name_or_path should be either **neuralmind/bert-base-portuguese-cased** or **neuralmind/bert-large-portuguese-cased**
