### ISSUE TITLE
Problem importing Model

### ISSUE THREAD

**Issue by victorciurlini** [neuralmind-ai/portuguese-bert#12]
i'm trying to import this model in jupyter notebook, but something went wrong and it returns me this message

    _348         # Get files from url, cache, or disk depending on the case

OSError: Model name 'neuralmind/bert-large-portuguese-cased' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed 'neuralmind/bert-large-portuguese-cased' was a path or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url._

cant figure out how to solve this.

**Comment by pvcastro** [comment]
@victorciurlini have you checked your transformers version? They support downloading community models from their repo only from a specific version. If I'm not mistaken is around 2.3.0 or 2.5.0, something like this. Try upgrading your transformers package.

**Comment by victorciurlini** [comment]
It works..thanks a lot.
