### ISSUE TITLE
Significado dos labels

### ISSUE THREAD

**Issue by moniquebm** [neuralmind-ai/portuguese-bert#18]
Com base em testes e no arquivo de configuração, só há 2 labels: LABEL_0 e LABEL_1.  Qual seria exatamente o significado deles? 
Seria este?

- LABEL_0   "O",       # Outside of a named entity
- LABEL_1   "B-MISC",  # Beginning of a miscellaneous entity right after another miscellaneous entity

(De acordo com exemplo no site do Huggingface)

Há previsão de evoluir o modelo para a inclusão de outros tipos de entidade?  (O BERT inclui 9).

**Comment by fabiocapsouza** [comment]
Olá @moniquebm , os checkpoints disponibilizados são dos modelos BERT pré-treinados para Português, que foram usados como checkpoint inicial dos modelos treinados na tarefa de NER. Em breve disponibilizaremos o código e os modelos de NER treinados no HAREM.
