### ISSUE TITLE
Download brWac and multilingual weights

### ISSUE THREAD

**Issue by flaviofafe1414** [neuralmind-ai/portuguese-bert#2]
Hello, excellent work. I have two questions. 1) Could you indicate where I can download brWac? tried by the link and found it unavailable. 2) What is the objective of starting with the multilingual weights? Just to increase the speed of convengence??

**Comment by pauloalves86** [comment]
1) The link can be found [here](http://www.inf.pucrs.br/linatural/wordpress/recursos-e-ferramentas/blogset-br/) and [that is what you want](http://www.inf.pucrs.br/linatural/blogs/blogset-br.csv.gz).

**Comment by fabiocapsouza** [comment]
1) Indeed, the link for brWaC is broken in their article. I did not save it, so I think it would be best to contact the authors.

2) Yes, it usually helps to start from a "working" checkpoint than from random weights.
