### ISSUE TITLE
What's max_len?

### ISSUE THREAD

**Issue by moniquebm** [neuralmind-ai/portuguese-bert#21]
In general, BERT-based models have a sequence maximum length = 512, but when I check:

tokenizer = AutoTokenizer.from_pretrained('neuralmind/bert-base-portuguese-cased')
tokenizer.max_len is equal to 1000000000000000019884624838656

It seems you don't have maximum sequence limits.  So, what's the right value to consider for max_len?

**Comment by fabiocapsouza** [comment]
Hi @moniquebm 
You're right, it should be 512.
