### ISSUE TITLE
Rename the project to BERTinho

### ISSUE THREAD

**Issue by diogofm** [neuralmind-ai/portuguese-bert#3]
I know it is funny, but please follow the global tendency:

French BERT: https://camembert-model.fr/ - Refers to the camembert cheese.
Spanish BERT: https://github.com/dccuchile/beto

Think about it!

**Comment by MarquesMan** [comment]
Acho que deveria se chamar BeBerto

**Comment by fabiocapsouza** [comment]
Obrigado pelas sugestões, mas já havíamos decidido por outro nome: BERTimbau
