### ISSUE TITLE
Download link access denied 

### ISSUE THREAD

**Issue by joao-luz** [neuralmind-ai/portuguese-bert#39]
None of the download links are working! I get the following message:
![image](https://user-images.githubusercontent.com/47804707/158367297-377e9c99-8f39-4777-ae9a-b65f4acf2538.png)

**Comment by fabiocapsouza** [comment]
Hi @Joao-Luz , unfortunately we had to remove the links because it was costing too much to host on AWS. If possible, please use the transformers lib instead.

**Comment by joao-luz** [comment]
Well, that's unfortunate. You should remove the broken links then

**Comment by robertoalotufo** [comment]
Hello João Luz

We updated the download links to point to the Hugging Face repository.
See if it is OK for you.
Thank you
Roberto

Em ter., 15 de mar. de 2022 às 10:04, Joao Luz ***@***.***>
escreveu:

**Comment by joao-luz** [comment]
@robertoalotufo It's great! Thank you so much for the quick response/edit!
