### ISSUE TITLE
Pretrained tokenizer does not recognize special characters `º` `ª`

### ISSUE THREAD

**Issue by jotapem** [neuralmind-ai/portuguese-bert#5]
If a word contains the special character `º` or `ª`, its token is decoded as `[UNK]` (unknown).

Code that demonstrates the issue:
```
from transformers import AutoTokenizer

model_dir = "models/portuguese-bert-lener_br"
tokenizer = AutoTokenizer.from_pretrained(model_dir)

def encode_decode(t):
    return tokenizer.decode(tokenizer.encode(t))

print(encode_decode("nº 396"))
print(encode_decode("n 396"))

print(encode_decode("Srª Maria"))
print(encode_decode("Sr Maria"))
```

Is there anything I am doing wrong or is the model incapable of embedding words containing such characters?

**Comment by fabiocapsouza** [comment]
Hi jotapem,

Sorry for the delayed response. Yes, unfortunately these symbols were not included in the generated WordPiece vocabulary.

**Comment by jotapem** [comment]
Thank you for the answer.
